data:
  object_folder: "/home/alexm/Projects/AMR_Semesterprojekt/AMR_project/scan_objects"
  save_folder: "/home/alexm/Projects/AMR_Semesterprojekt/AMR_project/pointcloud_files"

scan_settings:
  num_scans: 5
  object_location: [0,0,0]
  scanner_location: [0,-6,1]