data:
  object_folder: '/home/alexm/Projects/AMR_Semesterprojekt/AMR_project/scan_objects'
  save_folder: '/home/alexm/Projects/AMR_Semesterprojekt/AMR_project/pointcloud_files'

scan_settings:
  scanner_location: [0,-3.5,1]
  scanner_rotation: [70,0,0]
  object_location: [0,0,0]
  num_scans: 5

azure_kinect_settings:
  x_res: 640
  y_res: 576
  hor_fov: 75
  ver_fov: 65
  focal_length: 1.8
  max_scan_dist: 3.86
  noise_center: 0
  noise_sigma: 0
  
  