data:
  object_folder: "/home/student/PERSISTENT/AMR_project/scan_objects"
  save_folder: "/home/student/PERSISTENT/AMR_project/pointcloud_files"

scan_settings:
  num_scans: 1
  object_location: [0,0,0]
  scanner_location: [0,-6,1]